# Generated by Django 4.0.4 on 2022-05-14 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_contact_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
