# Generated by Django 4.0.4 on 2022-05-15 23:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000),
        ),
    ]
