# Generated by Django 4.0.4 on 2022-06-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, upload_to='profile_pictures', verbose_name='Picture'),
        ),
    ]
